export default async function Head() {
     return (
          <>
               <title>you</title>
               <meta name="description" content="Generated by head" />
               <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
               />

               <link rel="icon" href="/favicon.ico" />
          </>
     );
}
